### ISSUE TITLE
Open generated URL doesn't work in Firefox

### ISSUE THREAD

**Issue by andys8** [jspm/generator#168]
https://generator.jspm.io/#ZcxBDkAwEEDRWQinMQwhlr2EA9BOZKQqqamtq5OIle1L/s8zgOIag4p6djDLUkpQXjgawh47AsdWtsnjehiqsUWCyJPV0u2boQEbrH9QWS8c9O8Hx5Pj61+ckjgzPOPmBszFaRmMAA

works in latest Chrome, doesn't work in old Chrome and latest Firefox.

### Demo

https://user-images.githubusercontent.com/13085980/184556081-dd81d570-4802-4646-a404-b4800141d115.mp4

**Comment by guybedford** [comment]
The only diff that must have caused the issue is https://github.com/guybedford/es-module-shims/commit/15f745e4620a6baf2045e7053de93e896bffc05c.

In particular I think it can probably be traced down to just these 10 lines only: https://github.com/guybedford/es-module-shims/commit/15f745e4620a6baf2045e7053de93e896bffc05c#diff-d9f5f5cf3b132cd3d457a02a9202af63e78eb6b8b3284097e5d1cfd28b181e8eR499-R505

If you try running es-module-shims locally again with just that 10 line diff I've highlighted there reversed, that might demonstrate a fix.
